AspNet-MVC-Training/Controllers/TrainingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNet_MVC_Training.Models;
using AspNet_MVC_Training.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace AspNet_MVC_Training.Controllers
{
    public class TrainingsController : Controller
    {
        private readonly IdentityDataContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<TrainingsController> _logger;

        public TrainingsController(IdentityDataContext context, UserManager<ApplicationUser> userManager, ILogger<TrainingsController> logger)
        {
            _context = context;
            _userManager = userManager;
            _logger = logger;
        }

        // GET: Trainings
        public async Task<IActionResult> Index(string trainingCategory, string searchString)
        {
            // Use LINQ to get list of categories.
            IQueryable<string> categoryQuery = from m in _context.Training
                                            orderby m.Category
                                            select m.Category;

            var trainings = from t in _context.Training
                        select t;

            if (!string.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                trainings = trainings.Where(s => s.Title.ToLower().Contains(searchString));
            }

            if (!string.IsNullOrEmpty(trainingCategory))
            {
                trainingCategory = trainingCategory.ToLower();
                trainings = trainings.Where(x => x.Category.ToLower() == trainingCategory);
            }

            // Populate with Formers
            trainings = trainings.Include(t => t.Former);
            
            // Get User's registered formations
            List<int> registeredFormations = new List<int>();
            List<UserTraining> UserCart = new List<UserTraining>();
            ApplicationUser user = null;

            if (User.Identity.IsAuthenticated) {
              ApplicationUser userReq = await _userManager.GetUserAsync(User);
              // Populate UserTraining
              user = await _userManager.Users
                .Include(u => u.UserTrainings)
                .SingleAsync(u => u.Equals(userReq));

              if (user != null) {
                registeredFormations = user.UserTrainings.Where(ut => ut.Status != Status.Cart).Select(ut => ut.TrainingID).ToList();
                
                UserCart = user.UserTrainings.Where(ut => ut.Status == Status.Cart).ToList();
              }
            }

            var trainingCategoryVM = new TrainingCategoryViewModel
            {
                Categories = new SelectList(await categoryQuery.Distinct().ToListAsync()),
                Trainings = await trainings.ToListAsync(),
                UserFormations = registeredFormations,
                UserCart = UserCart,
                UserId = user != null ? user.Id : null
            };

            return View(trainingCategoryVM);
        }

        // GET: Trainings/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var training = await _context.Training
                .Include(t => t.Former)
                .FirstOrDefaultAsync(m => m.TrainingID == id);
            if (training == null)
            {
                return NotFound();
            }

            ApplicationUser userReq = await _userManager.GetUserAsync(User);
            ApplicationUser user = await _userManager.Users
              .Include(u => u.UserTrainings)
              .SingleAsync(u => u.Equals(userReq));
            
            if (!user.UserTrainings.Any(ut => (ut.TrainingID == id && ut.Status != Status.Cart))) {
              return RedirectToAction(nameof(Index));
            }

            ViewBag.Title = training.Title;

            return View(training);
        }

        // GET: Trainings/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trainings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(string Title, IFormFile Image, string Category, decimal Price, string Description, string Content, string Video)
        // public async Task<IActionResult> Create([Bind("TrainingID,Title,Image,ReleaseDate,Category,Price")] Training training)
        {
            Training training = new Training {
              Title = Title,
              Description = Description,
              Content = Content,
              Video = Video,
              ReleaseDate = DateTime.Now,
              Category = Category,
              Price = Price,
              Former = await _userManager.GetUserAsync(User)
            };

            if (Image != null && Image.Length > 0)  
            {
              var fileName = Path.GetFileName(Image.FileName);
              var fileUrl = Path.Combine("images", Guid.NewGuid().ToString() + "_" + fileName);
              var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", fileUrl);
              using (var fileStream = new FileStream(filePath, FileMode.Create))
              {
                  await Image.CopyToAsync(fileStream);
              }

              training.Image = fileUrl;
            }  

            UserTraining userTraining = new UserTraining {
              User = training.Former,
              Training = training,
              Status = Status.Finished
            };

            if (TryValidateModel(training, nameof(Training)))
            {
                _context.Add(training);
                _context.Add(userTraining);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(training);
        }

        // GET: Trainings/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);

            var training = await _context.Training.SingleOrDefaultAsync(t => t.UserId == user.Id && t.TrainingID == id);
            if (training == null)
            {
                return NotFound();
            }
            return View(training);
        }

        // POST: Trainings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int TrainingID, string Title, IFormFile Image, string Category, decimal Price, string Description, string Content, string Video)
        {
            Training training = new Training {
              TrainingID = TrainingID,
              Title = Title,
              Description = Description,
              Content = Content,
              Video = Video,
              ReleaseDate = DateTime.Now,
              Category = Category,
              Price = Price,
              Former = await _userManager.GetUserAsync(User)
            };

            var trainingQuery = await _context.Training.FindAsync(TrainingID);
            _context.Entry(trainingQuery).State = EntityState.Detached;

            string fileUrl = null;
            if (Image != null && Image.Length > 0)  
            {
              // Delete previous image
              new FileInfo(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", trainingQuery.Image)).Delete();

              // Save new image
              var fileName = Path.GetFileName(Image.FileName);
              fileUrl = Path.Combine("images", Guid.NewGuid().ToString() + "_" + fileName);
              var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", fileUrl);
              using (var fileStream = new FileStream(filePath, FileMode.Create))
              {
                  await Image.CopyToAsync(fileStream);
              }

            }
            training.Image = fileUrl ?? trainingQuery.Image;

            if (TrainingID != training.TrainingID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(training);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainingExists(training.TrainingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(training);
        }

        // GET: Trainings/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)

AspNet-MVC-Training/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using AspNet_MVC_Training.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Learn4Life</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Learn4Life</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                      @if (!SignInManager.IsSignedIn(User))
                      {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                      }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainings" asp-action="Index">Formations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Learn4Life
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>